channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=25.0
- pip:
  - mlflow==2.20.1
  - cloudpickle==3.1.1
  - numpy==1.26.2
  - psutil==6.1.0
  - scikit-learn==1.3.0
  - scipy==1.15.1
name: mlflow-env
